#!/bin/bash

# DIRECTORIES
mkdir /opt/rtmp/{hls,dash,store} -p

# NGINX
apt-get purge nginx-light nginx-common libnginx-mod-rtmp
apt-get install nginx-light nginx-common libnginx-mod-rtmp

# NGINX ( config )
curl https://raw.githubusercontent.com/yhale/configs/prod/nginx.conf -o /etc/nginx/nginx.conf